# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
  # Pods for GoogleLogin

end
